### ISSUE TITLE
Make `target` optional

### ISSUE THREAD

**Issue by emrynHofmannElephant** [ilias-ant/adversarial-validation#1]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]. Wouldn't be nice to be able to [...]?
I often store my target in a separate dataframe, e.g. y_train/y_test. For adversarial validation, this isn't needed - in fact, you drop it.

**Describe the solution you'd like**
Could the argument `target` be made optional, to allow for the case above? - Which would just involve a simple:
`if not isinstance(target,None): <drop>`

**Describe alternatives you've considered**
Another way to handle this would be to allow users to pass in target series/dataframes, but this seems a little pointless.

**Comment by ilias-ant** [comment]
Hi @emrynHofmannElephant and thank you so much for submitting this issue!

You are certainly right, since `target` is not used in the process, the code should gracefully ignore it (definitely not require it as you say).

Will try to upload the fix by the end of the week, until then you can just "pass" a dummy target

**Comment by ilias-ant** [comment]
@emrynHofmannElephant issue fixed!

Check with the latest version of the library `v1.0.1` =)

<img width="947" alt="image" src="https://github.com/user-attachments/assets/d78148f7-cf15-4c66-8622-d7b6039d58bb" />

**Comment by emrynHofmannElephant** [comment]
Thank you! :)
